### ISSUE TITLE
3.3 Validate AdM Tile data

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#22]
As @jrconlin [points out](https://github.com/mozilla-services/contile/pull/16#pullrequestreview-595504930): 

We might want to do some validation on a few of these fields, partly because it's external data that we're displaying on user machines, so there's a potential for mischief.

We can start w/ basic validation of the urls via the validator crate's [#[validate(url)]](https://github.com/Keats/validator#url)

**Comment by pjenvey** [comment]
When tiles fail to validate I think we should just "ignore" them (not caching them or returning them to the client), but we could also emit events to sentry about so they're not completely ignored.

**Comment by ncloudioj** [comment]
> When tiles fail to validate I think we should just "ignore" them (not caching them or returning them to the client), but we could also emit events to sentry about the invalid data so they're not completely ignored.

Agreed. Clients definitely do not need to see those malformed tiles. Though we might want to have some "negative" records in the cache so that Contile won't keep asking adM for the same problematic tiles over and over again during the cache window. Those negative cache records allow Contile to quickly respond to user's requests with "sorry, we don't have anything for you right now".

Sending a signal to Sentry is also desirable, with that we might be able to inform adM (or other partners) so that they can fix it on their side.

**Comment by ncloudioj** [comment]
> We should also do some validation to the query parameters included in Tile urls.

To begin with, I think we could validate the existence of those required query parameters, also make sure there is no unknown parameters in those URLs. For reference, [this](https://github.com/mozilla-services/quicksuggest-rs/blob/main/process-data.js#L43-L101) is how we validate impression/click URLs for Firefox QuickSuggset on RemoteSettings.
