### ISSUE TITLE
Log empty results

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#222]
We're seeing a higher number of empty return responses than we expected. We should record an error to sentry when we return an empty result to provide more information about why that's happening. (e.g. empty response from ADM, request error, etc.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1157)

**Comment by pjenvey** [comment]
We currently mask certain adm errors with empty results to the client however a sentry event is generated along side that empty result. AFAICT we're not seeing any of these events in sentry, so I think our empty responses are all due to empty adM results.

#92 had some discussion about propagating these errors to the client instead, we might want to begin doing that here.

**Comment by jrconlin** [comment]
Yeah, I was adding a bit of logic to include an non-interrupt error report that fires when we get empty tiles from ADM. I was debating adding a similar one post filter to record if we have no tiles that pass filters. I figure that might give us insight to the current situation without changes to the UA.

**Comment by pjenvey** [comment]
We generate a significant number of 204s (50-100 req/s) though -- an event for each one seems way too chatty for sentry.

**Comment by jrconlin** [comment]
Good point. Metric then? (Although I'm guessing we want to capture the location and device_info. )
