### ISSUE TITLE
Switch hasher to Blake3

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#228]
The default rust hasher library is "good enough" but there are several suggestions to use something better.  Blake is a fast hashing algorithm, and [Blake3](https://github.com/BLAKE3-team/BLAKE3) is a vast improvement.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1165)

**Comment by mythmon** [comment]
The improvements over SHA2 is very impressive! Do you know how it compares to something like `HighwayHash`, like I reviewed over on Merino? https://github.com/mozilla-services/merino/pull/82/files#diff-d55a8f64699c26b925529b5711141b7e5120b18abacd2cd7a40df9533af20406

**Comment by mythmon** [comment]
I did some benchmarking, and it turns out that Blake3 is quite a bit faster than even HighwayHash, while keeping all the network safety and potential DoS protections.

![image](https://user-images.githubusercontent.com/305049/127551752-5afa2106-395f-4268-9941-df954c4633e2.png)

I'm going to go update my ADR in the other PR. Thanks!
