### ISSUE TITLE
Investigate stage load testing failures

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#230]
Recent [load testing results](https://docs.google.com/document/d/10Hx4cGvGBvq0z0uOK_CG3ZcyaQnT_EtgR6MYXmIvG6Q/edit) show high level of failures that do not occur on production.

These may be due to the k8s cluster sizing itself to accommodate the load, but in my previous experience (syncstorage's k8s cluster) some initial errors are expected (see the [Sync load test history](https://docs.google.com/document/d/1dY7Jltgw9JvrytTvXjgHYUmzbZbrJyMVb3fBap6L8l8/edit)) but these seem higher.

Let's double check that these errors only happen on startup of the load test, the stage k8s cluster is sizing itself correctly, and consider how we can more easily verify the stage environment if these errors are inevitable.

We may need to adjust our expected failure rate and or pre-warm the cluster (e.g. by running a short load test for sizing followed by the lengthier load test).

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1166)

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Thank you Philip Jenvey for filing this!

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Philip Jenvey Jon Buckley Let’s decide an acceptable failure% because the ideal numbers( failure<0.001% = pass, failure>0.001% = fail) seems too aspirational for now and we haven’t achieved it yet.

**Comment by pjenvey** [comment]
This is no longer an issue on stage. It's possibly due to a couple of changes to the cluster:

- Its k8s cluster has disabled auto scaling and locked itself into one contile pod
- iprepd memory sizes were increased

@ashrivastava-qa has also seen some unrelated high failure rates but these appear to be due to a [contile-loadtester environment issue](https://github.com/aio-libs/aiohttp/issues/3535).
