### ISSUE TITLE
Add contract tests for tiles caching

### ISSUE THREAD

**Issue by ashrivastava-qa** [mozilla-services/contile#274]
Add test scenarios for tile caching in `volumes/client/scenarios.yml` file making use of responses from the `volumes/partner/response.yml` file (or by updating the `response.yml` file)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1232)
┆epic: Add Contract Test Coverage For Contile Cache

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

To add tile caching test there are two ways we could go about:
1. Add a test in which the client sends the first(new) request to Contile. Contile then first checks it in the cached files for an existing entry (with audience key : formfactor, OS, Country_code, region_code, dma, legacy Firefox version), since there isn’t a record yet, it then sends the request to the Partner and gets a response in return with a 200 Ok.
Now when the client again sends a request with the same formFactor and OS and this time finds an entry in the cached files (with the same audience key as well) it returns the same response as previous and doesn’t redirects the request to the partner. This fulfills the tile caching requirement. But to verify that this request indeed is coming from the cache and not the partner (since we have the resonse.yml file hardcoded), we need to verify that with a new request (with some different query parameters than before) the response received is different than before. To achieve the above scenario we need to change the main.py test and tweak it to make sure that we keep track(or a counter) of the requests we send out for a particular Formfactor and OS and checking the response against it.

2. The second test would be to store the history of requests and responses, i.e converting the stateless API to a stateful API.

**Comment by data-sync-user** [comment]
➤ Raphael Pierzina commented:

The second request needs to include information (User-Agent and X-Forwarded-For headers) that result in an identical cache audience key as for the first request. Not only form_factor and os_family. For example, a different IP address that results in the same geo location information would work. Or a different Firefox version that has or does not have legacy images depending on the first request (the exact Firefox version is not part of the audience key).

We can confirm that the tiles are in fact read from the cache if the partner API returns a different response to Contile for the same parameters, but Contile still returns the same tiles to the client. Note that this doesn’t consider the tiles TTL (time to live) for which there is a setting that we can control (tiles_ttl).

Regardless of which approach we go with, we will need to add state to the partner API. I suggest creating a GitHub issue at contile-integration-tests ( https://github.com/mozilla-services/contile-integration-tests/issues/new/choose ) for this capability and create a Jira ticket under the Testing component linking to the new GitHub issue and set it as a blocker for this one.

One detail to keep in mind for 2. is that the client test framework currently only supports sending requests to Contile. We can extend the format for scenarios.yml and the framework to support different hosts for requests. I lean towards option 2 because it doesn’t rely on embedding test information into the tiles responses. But there’s enough overlap between 1. and 2. that we can start with 1. and see if that solves our immediate problem.

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Not actively working on this task currently.

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

This ticket is up for grabs. I am not currently working on it due to other high priority items.
